/* 200 academic A/B items. Session picks 20 (5 per study axis).
   Axes are class habits, not personality: EI how you learn, SN what work you trust,
   TF how you judge an answer, JP how you run homework. */
(function (global) {
  function q(dim, prompt, promptZh, aTitle, aText, aTitleZh, aTextZh, bTitle, bText, bTitleZh, bTextZh) {
    var pair = { EI: ["E", "I"], SN: ["S", "N"], TF: ["T", "F"], JP: ["J", "P"] }[dim];
    return {
      dim: dim,
      prompt: prompt,
      promptZh: promptZh,
      a: { letter: pair[0], title: aTitle, text: aText, titleZh: aTitleZh, textZh: aTextZh },
      b: { letter: pair[1], title: bTitle, text: bText, titleZh: bTitleZh, textZh: bTextZh }
    };
  }

  var BANK = [
    /* —— EI: learn with others vs learn independently (25) —— */
    q("EI", "A school project starts. Which way do you actually work better?", "学校项目开始了。哪种方式你真正更顺？",
      "A team table", "Talk, split tasks, check with others as you go.", "一张小组桌", "边说边分活，一边做一边和别人核对。",
      "My own desk first", "Write your part alone, then share when it is ready.", "先自己的桌子", "先独立写完自己的部分，准备好了再分享。"),
    q("EI", "You do not understand a maths step. What do you do first?", "有一步数学没懂。你先做什么？",
      "Ask now", "Ask the teacher or a classmate while the idea is still warm.", "马上问", "趁还热着，问老师或同学。",
      "Re-read first", "Go back through the notes quietly. Ask only if you are still stuck.", "先重读", "安静地把笔记再看一遍。还是不懂再问。"),
    q("EI", "Revision week. What actually helps you remember?", "复习周。什么真能帮你记住？",
      "A quiz group", "Friends ask each other questions out loud.", "互相提问", "朋友大声互相提问。",
      "A quiet seat", "A library desk, headphones, your own list.", "安静座位", "图书馆座位、耳机、自己的清单。"),
    q("EI", "The teacher offers two homework formats. You pick…", "老师给两种作业形式。你会选……",
      "A 3-minute talk", "Stand up and explain it to the class.", "三分钟发言", "站起来讲给全班听。",
      "A one-page write-up", "Hand in writing. No audience.", "一页书面作业", "交书面作业。不用面对听众。"),
    q("EI", "Science class: you may choose the format.", "科学课：你可以选形式。",
      "Pair lab", "Talk through the method while you measure.", "两人实验", "一边量，一边把步骤说清楚。",
      "Solo paper lab", "The same experiment, but you write the method alone.", "独自纸上实验", "同样的实验，但你独自写步骤。"),
    q("EI", "A new idea pops up in class. First move?", "课上突然有了新想法。你先怎样？",
      "Say it", "Talking out loud helps you finish the thought.", "说出来", "大声说能帮你把想法说完。",
      "Note it", "Write it in the margin. Share when the sentence is clear.", "先记下", "写在空白处。句子清楚了再分享。"),
    q("EI", "English: you may pick the task.", "英语课：你可以选题。",
      "Class debate", "You think by answering someone in the room.", "课堂辩论", "你靠当场回应别人来想清楚。",
      "Close-reading essay", "You think by writing in quiet.", "细读作文", "你靠安静写作来想清楚。"),
    q("EI", "After a hard lecture, you learn more by…", "一堂很难的课结束后，你靠什么学得更多？",
      "Comparing notes", "Walk out with a friend and reconstruct the argument.", "对笔记", "和朋友一起把论点重新拼起来。",
      "Rewriting notes", "Sit down and recopy the argument in your own words.", "重写笔记", "坐下用自己的话把论点再写一遍。"),
    q("EI", "History: the teacher wants someone to explain a source now.", "历史课：老师希望有人现在就解释一份材料。",
      "Think on your feet", "You are fine starting while people listen.", "当场想", "有人听着，你也可以开始讲。",
      "A paragraph later", "You would rather hand in writing after you have checked it.", "稍后交一段", "你更想核对后再交书面段落。"),
    q("EI", "You may ask the teacher a question. How?", "你可以问老师一个问题。怎么问？",
      "In front of the class", "Other people might need the same answer.", "当着全班", "别人可能也需要同一个答案。",
      "After the bell", "A short private question feels cleaner.", "下课后再问", "私下短问感觉更清楚。"),
    q("EI", "A coding club has two tracks. You pick…", "编程社有两条线。你会选……",
      "Pair programming", "Two people, one screen, talk the bug out.", "结对编程", "两人一块屏幕，把 bug 说出来。",
      "Solo kata", "A quiet problem set you finish at your own pace.", "独自练习", "安静的题目，按自己的节奏做完。"),
    q("EI", "Geography fieldwork. You would rather…", "地理实地。你更想……",
      "Interview people", "Ask shop owners or classmates what they notice.", "采访别人", "问店主或同学他们注意到什么。",
      "Log measurements", "Count, map, and write the pattern yourself.", "自己记录", "自己数、画图、写下规律。"),
    q("EI", "The school offers extra help. You book…", "学校提供额外辅导。你约……",
      "A small seminar", "Five students plus a teacher, lots of talk.", "小研讨", "五个学生加老师，很多讨论。",
      "A one-to-one slot", "Just you and the teacher, or even a written reply.", "一对一", "只有你和老师，或者书面回复也行。"),
    q("EI", "Drama is not required. For a literature unit you still pick…", "戏剧不是必修。文学单元里你还是会选……",
      "Read-aloud / scene", "Hearing the words in a room helps.", "朗读或小品", "在房间里听见这些词更有帮助。",
      "Annotation at home", "Marking the text at a desk helps more.", "在家批注", "在书桌边标课文更有帮助。"),
    q("EI", "You must learn a new formula. Better for you:", "你必须学一个新公式。哪种更好？",
      "Teach a classmate", "Explaining it out loud locks it in.", "教给同学", "大声讲出来才能记住。",
      "Drill in silence", "Repeating examples on paper locks it in.", "安静刷题", "在纸上反复例题才能记住。"),
    q("EI", "A group chat for the class project. You…", "班级项目有个群聊。你会……",
      "Keep it lively", "You drop ideas as they arrive. Chat is part of thinking.", "让它热闹", "想到就丢进去。聊天也是思考的一部分。",
      "Mute and batch", "You read later and send one clear message.", "静音再汇总", "过后再看，发一条清楚的消息。"),
    q("EI", "Art class critique. You prefer…", "美术课点评。你更喜欢……",
      "Live round", "People walk the room and talk about work together.", "当场轮流", "大家走来走去，一起谈作品。",
      "Written notes", "Sticky notes or a form you fill in quietly.", "书面便条", "便利贴或表格，安静填写。"),
    q("EI", "You have a free study period. You go to…", "有一节自习。你去……",
      "The busy common room", "Background talk helps you start.", "热闹的公共区", "有人说话的背景，反而让你开始。",
      "An empty classroom", "Silence helps you start.", "空教室", "安静才能开始。"),
    q("EI", "Languages: oral test vs written paper. You feel more accurate in…", "语言：口试还是笔试。你觉得哪种更准？",
      "The oral", "Speaking in the moment shows what you know.", "口试", "当场说，才显出你会什么。",
      "The paper", "Writing lets you check the grammar first.", "笔试", "写下来可以先检查语法。"),
    q("EI", "A research task: first source. You…", "研究任务：第一个资料。你会……",
      "Ask a librarian / teacher", "A short conversation points you faster.", "问图书馆或老师", "短聊一下，指路更快。",
      "Search the catalogue", "You like finding the trail yourself first.", "自己查目录", "你想先自己找出线索。"),
    q("EI", "PE theory homework (not the sport itself). You’d rather…", "体育理论作业（不是运动本身）。你更想……",
      "Plan a team drill", "Explain the drill to classmates, then try it.", "设计小组练习", "先讲给同学听，再试做。",
      "Write a training log", "Track one body measurement or habit on paper.", "写训练日志", "在纸上记录一项身体数据或习惯。"),
    q("EI", "When a class discussion is messy, you…", "课堂讨论很乱时，你会……",
      "Jump in", "Talking is how you sort the mess.", "插进去说", "靠说话把乱局理顺。",
      "Wait and summarise", "You speak once, after the pieces are clear.", "等一等再总结", "等碎片清楚了，再说一次。"),
    q("EI", "Computer class: two ways to show you understood the loop.", "电脑课：两种方式证明你懂循环。",
      "Live demo", "Run it on the projector and answer questions.", "当场演示", "投影运行，并回答问题。",
      "Commented code", "Hand in code with notes. No talking.", "带注释的代码", "交带注释的代码。不用讲。"),
    q("EI", "You must remember dates for a history test. You…", "历史测验要记日期。你会……",
      "Make a quiz with a friend", "They ask, you answer, then swap.", "和朋友互相考", "他们问你答，再交换。",
      "Make a silent timeline", "A page of dates you recopy until it sticks.", "安静做时间线", "一页日期，抄到记住为止。"),
    q("EI", "The teacher says: office hours or a class Q&A. You use…", "老师说：答疑时间或全班问答。你会用……",
      "The class Q&A", "Hearing other people’s questions helps you too.", "全班问答", "听别人的问题对你也有帮助。",
      "Office hours", "A short queue, one precise question.", "答疑时间", "排短队，问一个精确的问题。"),

    /* —— SN: concrete classwork vs models / what-if (25) —— */
    q("SN", "A science write-up. What do you trust more?", "科学实验报告。你更信什么？",
      "The table of results", "Numbers you measured. What actually happened.", "结果表格", "你量到的数字。实际发生了什么。",
      "The model", "The idea that explains why it should happen that way.", "模型", "解释“为什么该这样”的那个想法。"),
    q("SN", "History homework. You would rather…", "历史作业。你更想……",
      "Stick to the source", "What this letter or photo actually shows.", "紧贴材料", "这封信或这张照片实际显示了什么。",
      "Ask ‘what if’", "How the story might have gone if one fact changed.", "问“如果”", "如果有一个事实变了，故事会怎样。"),
    q("SN", "Maths: two kinds of problem. You pick…", "数学：两种题。你会选……",
      "A worked example", "Same method, new numbers. You can follow the steps.", "例题变式", "同一方法、新数字。你可以跟着步骤走。",
      "An open puzzle", "No template. You invent a way in.", "开放谜题", "没有模板。你自己找入口。"),
    q("SN", "Geography: climate. You learn faster from…", "地理：气候。你学得更快的是……",
      "A real weather log", "Rainfall this month in your city.", "真实天气记录", "你所在城市这个月的降雨。",
      "A climate model", "A diagram of how the whole system might shift.", "气候模型", "整个系统可能怎样变化的示意图。"),
    q("SN", "English: the teacher asks what the poem is doing. You start with…", "英语：老师问这首诗在做什么。你先从……",
      "The exact lines", "Words, rhythm, a quote you can point to.", "原句", "词语、节奏、你可以指出来的一句。",
      "The big idea", "A theme or feeling the whole poem is circling.", "大意", "整首诗绕着转的主题或感觉。"),
    q("SN", "Design & technology. You’d rather…", "设计与技术。你更想……",
      "Build the prototype", "Cut, glue, test whether it stands.", "做原型", "剪、粘、测它站不站得住。",
      "Sketch the system", "How it could work in five years, on paper.", "画系统", "在纸上画它五年后可能怎样运转。"),
    q("SN", "Biology: you remember more from…", "生物：你记得更多的是……",
      "The specimen", "What you saw under the microscope.", "标本", "显微镜下你看见的。",
      "The theory", "The story of how cells are supposed to work.", "理论", "细胞“应该怎样工作”的那套说法。"),
    q("SN", "A news article in class. You notice first…", "课上读新闻。你先注意到……",
      "The facts", "Who, where, how many, what was measured.", "事实", "谁、哪里、多少、量到了什么。",
      "The pattern", "What this might mean next year.", "规律", "这可能意味着明年怎样。"),
    q("SN", "Computer science: two tasks.", "计算机科学：两个任务。",
      "Fix this bug", "A real program that fails on input 7.", "修这个 bug", "一个真实程序，输入 7 就会失败。",
      "Invent a feature", "A new idea the app does not have yet.", "发明功能", "应用里还没有的新点子。"),
    q("SN", "Economics-style question (even if you have not taken it).", "偏经济学的问题（就算你还没上过这门课）。",
      "A price in a shop", "Why this bottle costs more today.", "商店里的价格", "为什么这瓶东西今天更贵。",
      "A market model", "Supply, demand, a graph of ‘what happens if’.", "市场模型", "供给、需求、“如果这样会怎样”的图。"),
    q("SN", "Art: your next piece. You start from…", "美术：下一件作品。你从……开始。",
      "A real object", "A shoe, a window, light you can see now.", "真实物体", "一只鞋、一扇窗、此刻能看见的光。",
      "A concept", "A feeling or question, then you find a form for it.", "一个概念", "一种感觉或问题，再给它找形状。"),
    q("SN", "You must explain gravity to a younger student. You use…", "你要给低年级讲重力。你会用……",
      "A dropping pen", "Watch it fall. Count. Repeat.", "一支掉落的笔", "看它落下。数。再来一次。",
      "A thought picture", "Imagine a planet, an orbit, a ‘what if there was no Earth’.", "思想画面", "想象一颗行星、一条轨道、“如果没有地球会怎样”。"),
    q("SN", "Music (even if you are not in choir). You learn a piece by…", "音乐（就算你不在合唱团）。你学一首曲子靠……",
      "The notes on the page", "Count, repeat the bar until it is exact.", "谱上的音符", "数拍，反复小节直到准确。",
      "The shape of the song", "Mood, story, where it is going next.", "曲子的形状", "情绪、故事、下一句要去哪。"),
    q("SN", "A lab went wrong. You write…", "实验失败了。你写……",
      "What the instruments showed", "The thermometer, the mass, the time.", "仪器显示了什么", "温度计、质量、时间。",
      "A new hypothesis", "What we should try next time and why.", "新的假设", "下次该试什么，以及为什么。"),
    q("SN", "Languages: vocabulary. You prefer…", "语言：词汇。你更喜欢……",
      "Example sentences", "How the word is used in a real dialogue.", "例句", "这个词在真实对话里怎么用。",
      "A pattern rule", "A structure you can apply to many new words.", "一条规律", "可以套到很多新词上的结构。"),
    q("SN", "The teacher says ‘be creative’. You feel safer when…", "老师说“要有创意”。你更踏实时……",
      "There is a model to copy first", "A sample paragraph or diagram.", "先有范例", "一段范文或一张样图。",
      "The brief is wide open", "You like inventing the frame yourself.", "题目很宽", "你喜欢自己发明框架。"),
    q("SN", "Chemistry: two pages in the book. You linger on…", "化学：书上两页。你会停在……",
      "The method box", "Grams, millilitres, safety steps.", "步骤框", "克、毫升、安全步骤。",
      "The bonding diagram", "An idea of how atoms ‘want’ to sit.", "成键图", "原子“想”怎样排的那个想法。"),
    q("SN", "A city-planning mini task. You’d rather…", "一个城市规划小任务。你更想……",
      "Walk and count", "Benches, buses, how people actually move.", "走一走再数", "椅子、公交、人实际怎么走。",
      "Redraw the future street", "A map of how it could feel in ten years.", "重画未来的街", "十年后可能给人什么感觉的地图。"),
    q("SN", "When you read a textbook, you look first at…", "读课本时，你先看……",
      "The example", "A fully worked case.", "例题", "一道完整算过的例子。",
      "The overview", "The chapter’s big claim.", "总览", "这一章的大主张。"),
    q("SN", "PE / sport science (the written bit). You pick…", "体育/运动科学（书面部分）。你会选……",
      "A training diary", "Heart rate, sleep, what you did on Tuesday.", "训练日记", "心率、睡眠、周二做了什么。",
      "A theory of fitness", "Why a body adapts — the idea, not the log.", "健身理论", "身体为什么会适应——是想法，不是日志。"),
    q("SN", "A coding comment. You write…", "代码注释。你会写……",
      "What this line does now", "Input, output, the bug it fixes.", "这行现在做什么", "输入、输出、它修了哪个 bug。",
      "Why we might change it", "A future design note.", "为什么以后可能改", "一条未来的设计备注。"),
    q("SN", "Class trip to a museum. You spend longer on…", "去博物馆的课。你在……花更久。",
      "The object label", "Date, material, where it was found.", "展品说明", "年代、材料、在哪发现的。",
      "The room’s story", "What the curator is trying to make you feel.", "展厅的故事", "策展人想让你感到什么。"),
    q("SN", "You must choose a science-fair question. You pick…", "你要选科学展题目。你会选……",
      "Measure something local", "How fast ice melts in our playground.", "测量身边的东西", "校园里冰化得有多快。",
      "A big unknown", "Could we live on Mars — a model, not a trip.", "一个大未知", "我们能不能住在火星——是模型，不是真去。"),
    q("SN", "When instructions are missing, you…", "说明书缺了时，你会……",
      "Copy a method you already used", "Last week’s lab, same steps.", "套用用过的方法", "上周的实验，同样步骤。",
      "Invent a new path", "You like designing the missing steps.", "发明新路", "你喜欢自己设计缺的步骤。"),
    q("SN", "A graph in class. You care more about…", "课上的图。你更关心……",
      "The plotted points", "Whether the dots were measured fairly.", "描出的点", "这些点量得公不公平。",
      "The trend line", "The story the slope is trying to tell.", "趋势线", "斜率想讲的故事。"),

    /* —— TF: proof / correctness vs people / meaning (25) —— */
    q("TF", "Your essay feedback is mixed. You look first at…", "作文评语好坏都有。你先看……",
      "Is the argument true?", "Logic, evidence, whether a sentence overclaims.", "论点成立吗？", "逻辑、证据、有没有一句话说过头。",
      "Did it treat people fairly?", "Tone, whose story is missing, whether it is kind.", "对人公平吗？", "语气、谁的故事缺了、是否善意。"),
    q("TF", "A group member’s slide is wrong. You…", "组员的幻灯片有错。你会……",
      "Correct the fact", "The number is false. Fix it, even if it feels blunt.", "改正事实", "数字是错的。改掉，就算有点直。",
      "Protect the person", "Ask privately. Keep the team feeling okay.", "照顾那个人", "私下问。让组里气氛还好。"),
    q("TF", "Biology ethics: animal testing in a text. You weigh…", "生物伦理：课文里的动物实验。你更看重……",
      "The data quality", "Did the method actually prove the claim?", "数据质量", "方法真的证明了那个主张吗？",
      "The harm", "What happened to the animals, and was it justified.", "伤害", "动物遭遇了什么，这样做站不站得住。"),
    q("TF", "A debate motion. You prepare by…", "一场辩论题。你准备时……",
      "Building proof", "Definitions, examples, holes in the other side.", "堆证据", "定义、例子、对方的漏洞。",
      "Finding the human stake", "Who is hurt or helped if this policy wins.", "找到对人的影响", "如果这政策赢了，谁受伤、谁受益。"),
    q("TF", "Maths: two students disagree. You trust…", "数学：两个同学意见不同。你更信……",
      "The proof", "Show the steps. One of them must be false.", "证明", "把步骤写出来。总有一个是错的。",
      "How they feel about it", "Maybe both are trying; check they are not shut down.", "他们的感受", "也许两人都在努力；别让人被堵死。"),
    q("TF", "You mark a classmate’s paragraph (peer review).", "你给同学的段落写互评。",
      "Accuracy first", "Spelling of names, dates, whether the quote is exact.", "先看准确", "人名拼写、日期、引文是否一字不差。",
      "Voice first", "Did it sound like them? Was it brave?", "先看声音", "听起来像他们自己吗？够不够勇敢？"),
    q("TF", "A school rule is unpopular. In civics class you argue…", "一条校规很不受欢迎。公民课上你主张……",
      "Does it work?", "Evidence: lateness numbers, safety, fairness of the test.", "它有用吗？", "证据：迟到次数、安全、考试公不公平。",
      "How people experience it", "Stress, belonging, who gets punished more.", "人怎么经历它", "压力、归属、谁更容易被罚。"),
    q("TF", "Computer class: the program works but the comments are rude. You…", "电脑课：程序能跑，但注释很不客气。你会……",
      "Keep the working code", "Correctness is the grade. Tone is extra.", "留下能跑的代码", "对才是分数。语气是额外的。",
      "Rewrite the tone", "A teammate has to read this. Kindness is part of the work.", "改语气", "队友要读。善意也是作业的一部分。"),
    q("TF", "History: two sources clash. You decide by…", "历史：两份材料冲突。你靠……决定。",
      "Which is better evidenced", "Date, author, what can be checked.", "哪份证据更好", "日期、作者、什么能被核实。",
      "Whose voice was silenced", "Who did not get to write a source.", "谁的声音被压了", "谁没机会写下材料。"),
    q("TF", "You must choose a science-club project. You pick the one that…", "你要选科学社项目。你会选那个……",
      "Has a clean test", "You can prove it yes or no.", "测试很干净", "你可以证明是或不是。",
      "Helps someone", "A real person in school might use it.", "能帮到人", "学校里真的有人可能用到。"),
    q("TF", "Feedback from a teacher is one sentence. You want it to be…", "老师只给一句评语。你希望它是……",
      "What is incorrect", "The exact error, so you can fix it.", "哪里不对", "精确的错误，好让你改。",
      "How to keep going", "Encouragement plus one next step.", "怎样继续", "鼓励，再加下一步。"),
    q("TF", "A graph looks impressive but the sample is tiny. You…", "图看起来很炫，但样本很小。你会……",
      "Call it out", "The claim is too big for the data.", "指出来", "数据撑不起这么大的主张。",
      "Ask who it affects", "Even a small sample might be someone’s life.", "问它影响谁", "就算样本小，也可能是某人的生活。"),
    q("TF", "Literature: a character does something cruel. You write about…", "文学：一个角色做了残忍的事。你写的是……",
      "Whether the plot is consistent", "Does the book’s logic hold?", "情节是否自洽", "书的逻辑站不站得住？",
      "The hurt", "What it would feel like to be the other person.", "伤害", "如果是对方，会是什么感觉。"),
    q("TF", "You are captain of a class project. A late teammate…", "你是班级项目组长。有人迟交……",
      "Gets a clear consequence", "Deadlines are the rule. The work has to be true.", "有清楚的后果", "截止日期就是规则。作业必须真实。",
      "Gets a private check-in", "Maybe something is hard at home.", "私下问一句", "也许家里有难处。"),
    q("TF", "Chemistry: two lab partners. One is faster and a bit sharp. You value…", "化学：两个实验搭档。一个更快、有点冲。你更看重……",
      "The faster method", "Right answers, less wasted time.", "更快的方法", "答案对，少浪费时间。",
      "The kinder pace", "Nobody is scared to ask a question.", "更温和的节奏", "没有人不敢提问。"),
    q("TF", "A statistic in a magazine is shocking. You first…", "杂志里一个统计数字很惊人。你先……",
      "Check the method", "Who was counted? Compared to what?", "查方法", "数了谁？和什么比？",
      "Think of a person", "What would this number mean for someone you know.", "想到一个人", "这个数字对你认识的人意味着什么。"),
    q("TF", "Design: a poster for a school event. You care more that it is…", "设计：学校活动海报。你更在意它……",
      "Clear and correct", "Time, room, no false claim.", "清楚正确", "时间、地点、没有假信息。",
      "Welcoming", "A shy first-year would dare to come.", "让人感到欢迎", "害羞的新生也敢来。"),
    q("TF", "In a mock trial (even in English class), you would rather be…", "模拟法庭（就算在英语课）。你更想当……",
      "The lawyer on facts", "Cross-examine the evidence.", "抓事实的律师", "盘问证据。",
      "The one who speaks for a person", "Make the jury see a life, not only a file.", "替一个人说话的", "让陪审团看见一个生命，而不只是档案。"),
    q("TF", "You got 90% but one comment says ‘cold’. You…", "你考了 90%，但有评语说“冷”。你会……",
      "Keep the 90 method", "Marks come from being right.", "继续 90 分那套", "分数来自做对。",
      "Warm the next piece", "Connection is part of a good answer.", "下一篇写得更有温度", "连接感也是好答案的一部分。"),
    q("TF", "Environmental science: a factory vs a river. Your essay leads with…", "环境科学：工厂对河流。你的作文先写……",
      "The measurements", "Oxygen, waste, what the tests show.", "测量数据", "氧气、废物、测试显示什么。",
      "The community", "Who fishes there, who works at the plant.", "社区", "谁在那里钓鱼，谁在厂里上班。"),
    q("TF", "A classmate used AI and the facts are wrong. You…", "同学用了 AI，事实是错的。你会……",
      "Flag the errors", "Wrong is wrong, tool or not.", "标出错误", "错就是错，不管什么工具。",
      "Ask why they were stuck", "Help them redo it without shame.", "问他们卡在哪", "帮他们重做，不让他们丢脸。"),
    q("TF", "Music or art jury (or a class critique). You comment on…", "音乐或美术评审（或课堂点评）。你评论……",
      "Technique", "Timing, proportion, whether it ‘works’.", "技术", "节奏、比例、它“成不成”。",
      "What it meant", "Did it move anyone? Was it honest?", "它意味着什么", "打动人了吗？诚实吗？"),
    q("TF", "You must pick a club to help with homework. You join…", "你要选一个能帮作业的社团。你加入……",
      "Olympiad / debate evidence", "Train to be precise under pressure.", "奥赛或证据型辩论", "练在压力下仍然精确。",
      "Peer mentoring", "Explain things so a younger student is not lost.", "同伴辅导", "讲到低年级同学不再迷路。"),
    q("TF", "A case study about a hospital. You notice first…", "一个关于医院的案例。你先注意到……",
      "The protocol", "Was the procedure followed? Data?", "流程", "步骤有没有按做？数据呢？",
      "The patient", "Were they scared, informed, respected?", "病人", "他们害怕吗、知情吗、被尊重吗？"),
    q("TF", "When two answers both ‘work’, you choose the one that is…", "两个答案都能“用”时，你会选那个……",
      "More logically tight", "Fewer holes, cleaner proof.", "逻辑更紧", "漏洞更少，证明更干净。",
      "More humane", "Easier on real people who have to live with it.", "更人道", "对必须承受结果的人更温和。"),

    /* —— JP: planned schoolwork vs flexible / exploratory (25) —— */
    q("JP", "A two-week project. On day one you…", "一个为期两周的项目。第一天你会……",
      "Make a calendar", "Tasks, dates, who does what. Finish early if you can.", "做日历", "任务、日期、谁做什么。能早完成就早完成。",
      "Explore first", "Read around, sketch, start when it clicks.", "先逛一逛", "先到处读、画草图，感觉对了再开始。"),
    q("JP", "Homework tonight. You…", "今晚的作业。你会……",
      "Do the set list in order", "Tick boxes. Then free time.", "按清单顺序做", "打勾。然后再自由时间。",
      "Start with the interesting bit", "The rest finds a place later.", "先做有意思的", "其余的稍后会有位置。"),
    q("JP", "The teacher gives a rubric. You feel…", "老师给了评分标准。你觉得……",
      "Safer", "You know exactly what ‘done’ looks like.", "更安心", "你清楚“完成”长什么样。",
      "A bit boxed in", "You like leaving room to change the plan.", "有点被框住", "你想留一点改计划的空间。"),
    q("JP", "Revision for a test. Your style is…", "备考。你的风格是……",
      "A timetable", "Chapter 3 on Monday, past paper on Tuesday.", "时间表", "周一第 3 章，周二真题。",
      "Follow energy", "Tonight geometry, because it clicked. History tomorrow.", "跟着状态", "今晚做几何，因为突然通了。历史明天再说。"),
    q("JP", "A long essay. You prefer…", "一篇长作文。你更喜欢……",
      "Outline first", "Introduction, three points, conclusion — then write.", "先列提纲", "引言、三点、结尾——再写。",
      "A messy draft", "Write, cut, reshuffle. Structure appears later.", "乱草稿", "写、剪、重排。结构后面才出现。"),
    q("JP", "Lab report due Friday. On Wednesday you are…", "实验报告周五交。周三你已经……",
      "Mostly drafted", "Graphs in, method written, time to check.", "大部分写好了", "图在、步骤写了，还有时间检查。",
      "Still collecting", "One more measurement might change the story.", "还在收集", "再一个测量可能改变故事。"),
    q("JP", "Group work: someone wants to change the topic on day 5. You…", "小组作业：有人第 5 天想换题。你会……",
      "Protect the plan", "We already divided the work. Stick to it.", "保住计划", "活已经分好了。按原计划。",
      "Allow the turn", "A better idea is worth a new map.", "允许转弯", "更好的点子值得重画一张图。"),
    q("JP", "You pack your bag the night before. You…", "前一晚收拾书包。你会……",
      "Check the timetable twice", "Books in the order of lessons.", "课表核对两遍", "书按上课顺序放。",
      "Grab what you need in the morning", "You adapt if a lesson changes.", "早上再抓", "如果课变了，你再适应。"),
    q("JP", "A coding project. You like…", "编程项目。你喜欢……",
      "Milestones", "Week 1 input, week 2 display, week 3 polish.", "里程碑", "第 1 周输入，第 2 周显示，第 3 周打磨。",
      "A sandbox", "Try three wild ideas, keep the one that works.", "沙盒", "试三个狂点子，留下能跑的那个。"),
    q("JP", "The brief says ‘any topic’. You…", "题目说“任何主题”。你会……",
      "Pick tonight and lock it", "Decision made. Research can start.", "今晚选定并锁定", "决定了。可以开始查。",
      "Keep two options warm", "You decide after a bit more reading.", "留两个选项", "再读一点再决定。"),
    q("JP", "Class has a surprise quiz. You feel…", "课上突然测验。你觉得……",
      "Annoyed", "You study better when you know the date.", "烦", "你知道日期时，复习更好。",
      "Awake", "A pop quiz is a fair snapshot of now.", "醒着", "突击测验是对现在的公平快照。"),
    q("JP", "Art coursework. You prefer…", "美术课业。你更喜欢……",
      "A series with a plan", "Sketch 1, 2, 3 — then the final.", "有计划的系列", "草图 1、2、3——再出成品。",
      "Follow the piece", "The work tells you the next step.", "跟着作品走", "作品告诉你下一步。"),
    q("JP", "You have three homework subjects. You…", "你有三科作业。你会……",
      "Time-box each", "25 minutes, then switch, even if unfinished.", "每科限时", "25 分钟，然后换，就算没做完。",
      "Stay with the one that flows", "Finish that river, then the others.", "停在顺的那科", "把这条河做完，再做别的。"),
    q("JP", "A presentation is in two weeks. You…", "两周后要演讲。你会……",
      "Write slides this weekend", "Rehearse next week. Buffer for disaster.", "这周末写幻灯片", "下周彩排。给意外留缓冲。",
      "Collect ideas until later", "The talk comes together near the date.", "想法先攒着", "临近日期，演讲会自己成形。"),
    q("JP", "Instructions are 12 steps. You…", "说明书有 12 步。你会……",
      "Follow them in order", "Tick each step. Do not skip.", "按顺序做", "每步打勾。不跳。",
      "Skip to the interesting step", "You loop back if something breaks.", "跳到有意思的一步", "坏了再绕回来。"),
    q("JP", "Weekend before exams. Your calendar is…", "考试前的周末。你的日历是……",
      "Full and labelled", "Slots for each subject.", "排满并标好", "每科都有时段。",
      "Mostly empty on purpose", "You leave space for what the week taught you.", "故意留空", "给这周新教会你的东西留位置。"),
    q("JP", "A teacher extends the deadline. You…", "老师延期了。你会……",
      "Still hit the old date", "Your plan does not need the extra days.", "仍赶原日期", "你的计划不需要多出来的几天。",
      "Use the extra days", "Another draft might get better.", "用上多的几天", "再一稿可能会更好。"),
    q("JP", "Group chat: ‘shall we meet?’ You reply…", "群里问“见面吗？”你回……",
      "A time and agenda", "4pm, library, finish section 2.", "时间和议程", "下午 4 点，图书馆，做完第 2 部分。",
      "Whenever / we’ll see", "Show up and decide then.", "随时 / 到时再说", "到了再决定。"),
    q("JP", "You lose a worksheet. You…", "你丢了一张作业纸。你会……",
      "Hate the chaos", "You reprint and file it the same hour.", "讨厌这种乱", "同一小时打印并归档。",
      "Improvise", "You reconstruct from memory and move on.", "临场发挥", "凭记忆补上，继续往前。"),
    q("JP", "Choosing next year’s subjects. You want…", "选明年的科目。你想要……",
      "A clear path", "These three subjects point at a known university door.", "一条清楚的路", "这三科指向一扇已知的大学门。",
      "Room to switch", "You like keeping a subject that might surprise you.", "留换的空间", "你想留一科，可能会带来惊喜。"),
    q("JP", "A science investigation. You like the moment when…", "科学探究。你喜欢的时刻是……",
      "The method is locked", "Everyone knows the steps. Now run them.", "方法锁定了", "每个人都知道步骤。现在执行。",
      "The method is still open", "You can still change the question.", "方法还开着", "你还可以改问题。"),
    q("JP", "Notes: folders vs one notebook. You use…", "笔记：文件夹还是一本本子。你用……",
      "Folders / colour tabs", "Each subject has a place. Easy to find.", "文件夹 / 彩签", "每科有位置。好找。",
      "One running notebook", "Ideas sit next to each other. You find them by memory.", "一本连续的本子", "想法挨着。靠记忆找。"),
    q("JP", "The lesson plan changes mid-class. You…", "课上中途改计划。你会……",
      "Want the original back", "You prepared for the posted plan.", "想回到原计划", "你按公布的计划准备的。",
      "Enjoy the turn", "A live change can be the real lesson.", "喜欢这个转弯", "当场改变，可能才是真正的课。"),
    q("JP", "You finish a past paper. Next you…", "你做完一套真题。接下来你会……",
      "Mark and file it", "Score, mistakes list, done.", "批改并归档", "分数、错题表、结束。",
      "Try a different paper", "Another angle while you are still in the mood.", "再做一套不同的", "趁还在状态，换一个角度。"),
    q("JP", "A design brief has a hard deadline and a vague goal. You first…", "设计任务截止日期很硬、目标很糊。你先……",
      "Turn the goal into a checklist", "Make the vague thing measurable.", "把目标变成清单", "让模糊的东西可测量。",
      "Play until a goal appears", "Making shows you what the brief wanted.", "做到目标自己出现", "做的过程会告诉你题目要什么。"),

    /* —— EI extra 26–50 —— */
    q("EI", "A reading club meets after school. You join if it is…", "课后有读书会。如果是……你会参加。",
      "A circle that talks", "People read a page, then argue it out loud.", "围坐讨论", "读一页，再大声争。",
      "A silent hour", "Everyone reads; you write a note to hand in.", "安静一小时", "大家自己读；你写一张纸条交上去。"),
    q("EI", "The teacher records a lesson video. You learn more if you…", "老师录了课。你学得更多是如果……",
      "Watch with a friend and pause to talk", "You check you both heard the same thing.", "和朋友一起看并暂停讨论", "确认你们听到的是同一件事。",
      "Watch alone and pause to note", "You write questions without waiting for anyone.", "自己看并暂停记笔记", "不等别人，自己写下问题。"),
    q("EI", "A translation task in languages. You’d rather…", "语言课的翻译。你更想……",
      "Trade lines with a partner", "You say a sentence; they say the next.", "和搭档对译", "你说一句，他们说下一句。",
      "Translate the whole page alone", "Then compare answers at the end.", "独自译完整页", "最后再对答案。"),
    q("EI", "School radio vs school newspaper. You pick…", "校园广播还是校报。你会选……",
      "The live mic", "You think while the red light is on.", "现场麦克风", "红灯亮着时你边想边说。",
      "The printed column", "You think while you edit the third draft.", "见报的专栏", "改第三稿时你才想清楚。"),
    q("EI", "A robotics kit arrives. First hour, you…", "机器人套件到了。第一个小时，你会……",
      "Build with two other people", "Hands and talk at the same table.", "和另外两个人一起装", "同一张桌上，手和嘴一起动。",
      "Read the manual at your bench", "You want the steps in your head first.", "在自己工位读说明书", "你想先把步骤装进脑子。"),
    q("EI", "You must learn a new citation style. You…", "你必须学一种新的引用格式。你会……",
      "Ask three classmates how they do it", "A short comparison in the corridor.", "问三个同学怎么做", "走廊里短短比较一下。",
      "Open the guide and copy one example", "Quiet, exact, no extra voices.", "打开指南抄一个例子", "安静、精确、没有多余的声音。"),
    q("EI", "A mock UN or model cabinet. You sign up to…", "模拟联合国或模拟内阁。你报名去……",
      "Speak on the floor", "You like the room hearing your clause.", "在会场发言", "你喜欢房间听见你的条款。",
      "Write the position paper", "You like the argument existing on the page first.", "写立场文件", "你喜欢论点先存在纸上。"),
    q("EI", "When a formula sheet is allowed, you still…", "允许带公式纸时，你还是会……",
      "Check it with a neighbour", "Did we copy the same version?", "和旁边的人对一下", "我们抄的是同一版吗？",
      "Keep your own copy private", "Your marks and arrows make sense only to you.", "自己的那份不给看", "你的记号只有你看得懂。"),
    q("EI", "A photography assignment. You prefer…", "摄影作业。你更喜欢……",
      "A shoot with a small crew", "Someone holds a light; you talk composition.", "一小队一起拍", "有人打灯；你们讨论构图。",
      "A solo walk with a camera", "You decide when to click, no committee.", "独自带相机走", "何时按下快门，不用开会。"),
    q("EI", "The library has two rooms. You sit in…", "图书馆有两个房间。你坐……",
      "The group-study room", "Whispers and a whiteboard help you start.", "小组自习室", "低语和白板帮你开始。",
      "The silent room", "Even a whisper breaks the work.", "静音室", "连低语都会打断工作。"),
    q("EI", "You have to memorise a speech. You practise by…", "你要背一篇演讲。你练习靠……",
      "Saying it to a person", "A face in the room tells you if it lands.", "说给一个人听", "房间里的一张脸告诉你有没有到位。",
      "Saying it to the wall", "You hear your own timing without an audience.", "对着墙说", "没有听众，你听自己的节奏。"),
    q("EI", "A data project: interview or spreadsheet? You lean to…", "数据项目：访谈还是表格？你偏向……",
      "Ten short interviews", "Talking people is how the numbers get meaning.", "十个短访谈", "和人说话，数字才有意义。",
      "A clean spreadsheet first", "Talk later, once the columns are honest.", "先做干净的表格", "列清楚了再去谈。"),
    q("EI", "Catch-up after you missed a class. You…", "缺课后补课。你会……",
      "Call a classmate", "A five-minute voice note is faster.", "打电话给同学", "五分钟语音更快。",
      "Read the slides twice", "You reconstruct the hour from the file.", "把幻灯片读两遍", "从文件把那一小时拼回来。"),
    q("EI", "A cooking / food-science practical. You like…", "烹饪或食品科学实践。你喜欢……",
      "A kitchen team", "One stirs, one times, you talk temperatures.", "厨房小组", "一个搅、一个计时，你们讨论温度。",
      "Your own station", "You control the heat without extra voices.", "自己的工位", "没有多余的声音，你自己控火。"),
    q("EI", "The school asks for a tour-guide volunteer. You…", "学校找导游志愿者。你会……",
      "Walk visitors and talk", "Questions from strangers wake you up.", "带着客人走并讲解", "陌生人的问题让你醒着。",
      "Write the tour script", "A clear page that someone else can read aloud.", "写导游词", "一页清楚的稿，别人可以照着念。"),
    q("EI", "When two methods both work in maths, you…", "数学里两种方法都能用时，你会……",
      "Explain both to the table", "Hearing which one clicks for others helps you too.", "向整桌解释两种", "听哪种对别人有用，对你也有帮助。",
      "Pick one and write it clean", "You do not need an audience to choose.", "选一种并写干净", "做选择不需要听众。"),
    q("EI", "A climate club. You would rather…", "气候社。你更想……",
      "Run a lunchtime stall", "Talk to people who stop.", "中午摆摊", "和停下来的人说话。",
      "Write the fact sheet", "A page people can take away in silence.", "写事实单页", "一页纸，人们可以安静拿走。"),
    q("EI", "You get stuck on a proof. After 10 minutes you…", "证明卡了。10 分钟后你会……",
      "Find a person", "A corridor question can unlock it.", "去找人", "走廊里问一句可能就开了。",
      "Find another book", "A second explanation, still alone.", "再找一本书", "第二种讲法，仍然是自己。"),
    q("EI", "Drama warmup is optional before English. You…", "英语课前戏剧热身可选。你会……",
      "Join the circle", "Moving and speaking with others opens the text.", "加入圆圈", "和别人一起动、说，课文才打开。",
      "Stay at your desk", "A quiet reread is enough warmup.", "留在座位", "安静重读就是热身。"),
    q("EI", "A statistics task. You check your mean by…", "统计任务。你检查平均数靠……",
      "Comparing with a partner", "If our numbers differ, we hunt the error together.", "和搭档比", "数字不同就一起找错。",
      "Recalculating twice yourself", "You trust a second pass more than a chat.", "自己再算两遍", "你更信第二次计算，而不是聊天。"),
    q("EI", "The teacher offers ‘office hours on voice chat or email’. You pick…", "老师说答疑可以用语音或邮件。你会选……",
      "Voice chat", "You think by talking the stuck bit out.", "语音", "把卡住的地方说出来才能想。",
      "Email", "You think by writing one precise question.", "邮件", "写一个精确的问题才能想。"),
    q("EI", "A map skills lesson. You prefer…", "地图技能课。你更喜欢……",
      "A pair orienteering course", "You call out bearings as you walk.", "两人定向", "边走边报方位。",
      "A solo grid exercise", "You plot points at a desk, then check.", "独自网格练习", "在桌上描点，再检查。"),
    q("EI", "When feedback arrives as a voice note, you…", "评语用语音发来时，你会……",
      "Like it", "Tone and extra sentences help.", "喜欢", "语气和多出来的句子有帮助。",
      "Wish it was text", "You want to scan it twice in silence.", "希望是文字", "你想安静扫两遍。"),
    q("EI", "A business-studies pitch. You’d rather…", "商科路演。你更想……",
      "Be the speaker", "The room is part of the work.", "当主讲", "房间是作业的一部分。",
      "Build the spreadsheet behind it", "The numbers should be ready before anyone talks.", "做背后的表格", "有人开口前，数字就该准备好。"),
    q("EI", "Last five minutes of class. You use them to…", "下课前五分钟。你用来……",
      "Ask one more question aloud", "Someone else might need it too.", "再当众问一个", "别人可能也需要。",
      "Star the unclear line in your notes", "You will look it up later, alone.", "在笔记里标出不懂的一行", "稍后自己去查。"),

    /* —— SN extra 26–50 —— */
    q("SN", "A river field trip. You fill the notebook with…", "去河边实地。你在本子上写……",
      "Width, speed, what you counted", "Things a second group could measure again.", "宽度、流速、你数到的", "第二组也能再量一遍的东西。",
      "A sketch of how the valley formed", "A story of ice, time, and ‘maybe’.", "河谷怎样形成的草图", "冰、时间、和“也许”的故事。"),
    q("SN", "You may choose the maths homework pack.", "你可以选数学习题包。",
      "Ten similar drills", "Same skill, new numbers, until it is automatic.", "十道相似练习", "同一技能、新数字，直到自动化。",
      "Two unusual problems", "No twin on the page. You invent a route.", "两道怪题", "页上没有双胞胎。你自己发明路线。"),
    q("SN", "A documentary in class. You take notes on…", "课上看纪录片。你记的是……",
      "Names, dates, what was filmed", "Checkable facts.", "人名、日期、拍到了什么", "能核对的事实。",
      "The director’s claim", "What they want you to believe next.", "导演的主张", "他们想让你接下来相信什么。"),
    q("SN", "Chemistry: unknown powder. You start with…", "化学：未知粉末。你先……",
      "Tests you can see", "Flame, melt, dissolve — results on the bench.", "看得见的测试", "火焰、熔化、溶解——桌上的结果。",
      "A theory of what it ‘should’ be", "A formula in the mind, then one test to check.", "它“应该是什么”的理论", "脑子里的分子式，再用一个测试核对。"),
    q("SN", "You design a school app. Day one you…", "你设计学校应用。第一天你会……",
      "List real complaints", "Queues, lost cards — problems you have seen.", "列出真实抱怨", "排队、丢卡——你见过的问题。",
      "Draw a future campus", "What school could feel like in five years.", "画未来校园", "五年后学校可能给人什么感觉。"),
    q("SN", "A poem has a footnote about a real war. You care more about…", "诗有一条关于真实战争的脚注。你更关心……",
      "The footnote’s facts", "Year, place, what happened.", "脚注里的事实", "年份、地点、发生了什么。",
      "The image the poet made", "How the war is being used as a symbol.", "诗人造的意象", "战争怎样被当成象征来用。"),
    q("SN", "Sports science lab: two options.", "运动科学实验：两个选项。",
      "Time a sprint with a stopwatch", "A number you can write in a table.", "用秒表测冲刺", "可以写进表格的数字。",
      "Model a ‘perfect’ stride", "A diagram of how a body might move.", "给“完美”步态建模", "身体可能怎样动的示意图。"),
    q("SN", "When a textbook chapter starts, you read first…", "课本一章开始时，你先读……",
      "The worked example box", "A full solution you can copy the shape of.", "例题框", "一个完整解答，你可以照它的形状。",
      "The ‘big idea’ paragraph", "Why this chapter exists.", "“大意”那一段", "这一章为什么存在。"),
    q("SN", "A seed-growing project. You get more excited by…", "种子种植项目。你更兴奋的是……",
      "Daily height in millimetres", "A graph that is only what grew.", "每天毫米高度", "一张只记录长了多少的图。",
      "A question about climate", "What this tray says about a hotter planet.", "一个关于气候的问题", "这个托盘对更热的地球说了什么。"),
    q("SN", "Architecture mini-task (even in art). You start by…", "建筑小任务（就算在美术课）。你先……",
      "Measuring the corridor", "How wide it is, how people actually walk.", "量走廊", "有多宽，人实际怎么走。",
      "Imagining a new wing", "A shape the school does not have yet.", "想象一座新侧楼", "学校还没有的形状。"),
    q("SN", "A news graph looks too smooth. You…", "新闻里的图太光滑。你会……",
      "Ask for the raw points", "Were they measured or guessed?", "要原始点", "是量的还是猜的？",
      "Ask what story they want", "Smooth often means a message.", "问他们想讲什么故事", "光滑常常意味着一种信息。"),
    q("SN", "Languages: you remember verbs better from…", "语言：动词你记得更牢是因为……",
      "A dialogue you acted", "Real sentences in a shop or kitchen.", "演过的对话", "商店或厨房里的真句子。",
      "A pattern table", "Endings you can apply to a new verb.", "一张规律表", "可以套到新动词上的词尾。"),
    q("SN", "You must explain electricity. You bring…", "你要讲电。你会带……",
      "A battery and a bulb", "Make it light. Then name the parts.", "电池和灯泡", "让它亮。再给零件起名。",
      "A field diagram", "Invisible arrows, then one real wire.", "场的示意图", "看不见的箭头，再加一根真电线。"),
    q("SN", "A history mystery: missing diary pages. You…", "历史谜题：日记缺页。你会……",
      "List what the remaining pages prove", "Only claims the paper can carry.", "列出剩下的页能证明什么", "只有纸张撑得住的主张。",
      "Invent the missing week", "A careful ‘might have’ that fits the person.", "发明缺的那一周", "一个谨慎的“可能”，还符合这个人。"),
    q("SN", "Coding: two tickets on the board.", "编程：板上两张任务单。",
      "Reproduce the crash", "Same clicks, same error, then patch.", "复现崩溃", "同样点击、同样错误，再打补丁。",
      "Redesign the flow", "A better path the user has not seen.", "重设计流程", "用户还没见过的更好路径。"),
    q("SN", "Music: learn a new piece. You start with…", "音乐：学新曲子。你先……",
      "Slow bars, metronome", "Correct notes before feeling.", "慢小节、节拍器", "先音准，再感觉。",
      "The mood and story", "Then you find which notes carry it.", "情绪和故事", "再找哪些音在承担它。"),
    q("SN", "A city heat map in geography. You look first at…", "地理里的城市热力图。你先看……",
      "The hottest measured street", "A number tied to a real road.", "测到最热的那条街", "绑在真实道路上的数字。",
      "The predicted 2050 layer", "A model of what might come.", "预测的 2050 图层", "可能到来的模型。"),
    q("SN", "You may pick the science-fair judge question. You want them to ask…", "你可以选科学展评委的问题。你希望他们问……",
      "How did you measure it?", "Units, repeats, error.", "你怎么量的？", "单位、重复、误差。",
      "What could this become?", "A leap from this tray to a bigger idea.", "这能变成什么？", "从托盘跳到一个更大的想法。"),
    q("SN", "English: a character’s house. You describe…", "英语：角色的房子。你描写……",
      "Doors, dust, the exact chair", "Things a camera could film.", "门、灰尘、那把椅子", "摄像机能拍到的东西。",
      "What the house stands for", "Safety, trap, memory — a meaning.", "房子代表什么", "安全、陷阱、记忆——一种含义。"),
    q("SN", "A broken printer in DT. You…", "设计课打印机坏了。你会……",
      "Test paper, ink, the jam", "Fix the real machine in front of you.", "测纸、墨、卡纸", "修好眼前这台真机器。",
      "Sketch a better printer", "How a future one should not jam.", "画一台更好的打印机", "未来的那台不该再卡纸。"),
    q("SN", "When the teacher says ‘estimate’, you prefer to…", "老师说“估算”时，你更想……",
      "Use last week’s measurement", "A number you already collected.", "用上周的测量", "你已经收集过的数字。",
      "Use a Fermi guess", "Powers of ten and a story of the world.", "用费米猜测", "十的几次方，加上一个关于世界的故事。"),
    q("SN", "A law-style case in class (no lawyer needed). You start from…", "课上一个法律式案例（不必当律师）。你从……开始。",
      "The given facts sheet", "Only what both sides agree happened.", "给定的事实单", "双方都同意发生过的事。",
      "A principle", "Fairness, harm, a rule you apply to new facts.", "一条原则", "公平、伤害、套到新事实上的规则。"),
    q("SN", "You remember chemistry bonds better as…", "化学键你记得更牢是当成……",
      "A kit you clicked together", "Balls and sticks on the desk.", "桌上扣在一起的套件", "球和棍。",
      "A rule about ‘wanting’", "Octets, energy, why atoms ‘seek’.", "一条关于“想要”的规则", "八隅体、能量、原子为什么“寻找”。"),
    q("SN", "A school garden plan. You would rather…", "校园园艺计划。你更想……",
      "Plant and weigh the harvest", "Grams of tomatoes in July.", "种下去并称收获", "七月番茄的克数。",
      "Design a food system", "How a whole year of meals could work.", "设计食物系统", "一整年的饭可以怎样运转。"),
    q("SN", "The last page of a lab is ‘further work’. You write…", "实验报告最后一页是“进一步工作”。你写……",
      "Repeat with a better thermometer", "Same question, cleaner tool.", "用更好的温度计再做", "同一问题，更干净的工具。",
      "A new question the data hints at", "The next mystery, not a repeat.", "数据暗示的新问题", "下一个谜，不是重复。"),

    /* —— TF extra 26–50 —— */
    q("TF", "A classmate’s model is beautiful but the scale is wrong. You say…", "同学的模型很好看，但比例错了。你会说……",
      "The scale error first", "Wrong numbers mislead the class.", "先说比例错", "错误的数字会误导全班。",
      "The care they took first", "Then mention scale so they can hear it.", "先说他们很用心", "然后再提比例，好让他们听得进去。"),
    q("TF", "A charity poster uses a shocking photo. In media class you ask…", "公益海报用了震撼照片。媒体课上你问……",
      "Is the claim true?", "Source, date, was anyone paid to pose.", "主张是真的吗？", "来源、日期、有没有人被付钱摆拍。",
      "Is it respectful?", "Would you want your face used that way.", "尊重人吗？", "你愿意自己的脸被这样用吗。"),
    q("TF", "Two lab partners: one is exact, one is encouraging. For a marked write-up you want…", "两个实验搭档：一个精确，一个会鼓励。计分报告你更想要……",
      "The exact one", "Marks come from method and digits.", "精确的那个", "分数来自方法和数字。",
      "The encouraging one", "You write better when you are not scared.", "会鼓励的那个", "你不害怕时写得更好。"),
    q("TF", "A school AI detector flags your essay. You care first about…", "学校 AI 检测标了你的作文。你先在意……",
      "Whether the charge is proven", "False positives, evidence, a clear process.", "这个指控有没有被证明", "误报、证据、清楚的流程。",
      "How it made you feel", "Trust, shame, whether anyone asked you first.", "它让你什么感觉", "信任、羞愧、有没有人先问你。"),
    q("TF", "In a group, someone is quiet. When grades are shared, you…", "小组里有人很安静。分数公开时，你会……",
      "Split by who did the proof", "Credit the work that is on the page.", "按谁做了证明来分", "把功劳给纸上的工作。",
      "Split so nobody is erased", "Quiet work still counts as care.", "分到没有人被抹掉", "安静的劳动也算用心。"),
    q("TF", "A history textbook skips a painful event. You write the teacher…", "历史课本跳过一件痛苦的事。你给老师写……",
      "A list of missing sources", "What should be added to be accurate.", "一份缺的材料清单", "为了准确，该补什么。",
      "Who is hurt by the silence", "Which families do not see themselves.", "沉默伤害了谁", "哪些家庭看不见自己。"),
    q("TF", "You peer-review code. Your first comment is about…", "你互评代码。第一条评论关于……",
      "A bug", "It fails on empty input. Fix that.", "一个 bug", "空输入会失败。先修这个。",
      "A teammate’s confidence", "They tried; here is one kind next step.", "队友的信心", "他们试了；这里有一步善意的下一步。"),
    q("TF", "A nutrition project uses celebrity advice. You…", "营养项目用了明星建议。你会……",
      "Demand a study", "N, control group, or it is not evidence.", "要求一项研究", "样本、对照组，否则不是证据。",
      "Ask who it might harm", "A diet tip can hurt a classmate.", "问它可能伤害谁", "一条饮食建议可能伤到同学。"),
    q("TF", "The class votes on a trip. Your speech is mostly…", "全班投票去哪春游。你的发言大多是……",
      "Cost, time, safety numbers", "Can we actually do this?", "费用、时间、安全数字", "我们真的做得到吗？",
      "Who gets left out", "Money, mobility, fear of crowds.", "谁会被落下", "钱、行动、怕人多。"),
    q("TF", "A translation is grammatically perfect but cold. You mark it…", "译文语法完美但很冷。你会评……",
      "High for accuracy", "The job was to be correct.", "准确度给高分", "任务是正确。",
      "Lower for voice", "The job was also to sound human.", "语气给低分", "任务也包括听起来像人。"),
    q("TF", "A science claim is trendy on social media. You first…", "科学主张在社交上很火。你先……",
      "Find the paper", "Methods, sample, who paid.", "找那篇论文", "方法、样本、谁出钱。",
      "Think of a younger sibling", "Would this scare or help them.", "想到更小的弟弟妹妹", "这会吓到他们还是帮到他们。"),
    q("TF", "Design a playground rule. You start from…", "设计一条操场规则。你从……开始。",
      "What reduces accidents", "Data from last term’s injuries.", "什么能减少事故", "上学期受伤的数据。",
      "What still feels like play", "A rule that does not crush joy.", "怎样仍然像玩", "一条不把快乐压死的规则。"),
    q("TF", "Someone used your idea without a name. You want the teacher to…", "有人用了你的点子却没写名字。你希望老师……",
      "Correct the record", "Truth about who thought it.", "改正记录", "关于是谁想到的真相。",
      "Mend the friendship", "A private talk so the group can work.", "修补友谊", "私下谈，好让组还能合作。"),
    q("TF", "A biology diagram of a body. You notice if it is…", "生物人体图。你会注意它是不是……",
      "Labelled correctly", "Wrong arrow, wrong grade.", "标注正确", "箭头错了，分数就错。",
      "Kind to real bodies", "Does it make anyone in class feel wrong.", "对真实身体友善", "会不会让班上某人觉得自己不对。"),
    q("TF", "The debate is ‘phones in class’. You prepare…", "辩论题是“课上用手机”。你准备……",
      "Studies on scores", "What the numbers say about learning.", "关于分数的研究", "数字对学习怎么说。",
      "Stories from anxious kids", "What a ban feels like at 16.", "焦虑同学的故事", "16 岁时禁令是什么感觉。"),
    q("TF", "A group slideshow has a joke that punches down. You…", "小组幻灯片有个向下打的笑话。你会……",
      "Cut it for accuracy of tone", "It weakens the argument.", "因语气不准确而删", "它削弱论点。",
      "Cut it because someone will flinch", "Harm is enough reason.", "因为有人会缩而删", "伤害本身就够理由。"),
    q("TF", "You got full marks and a note: ‘too sharp with your partner’. You…", "你满分，但评语写“对搭档太冲”。你会……",
      "Keep the sharp method", "The experiment was right.", "继续冲的那套", "实验是对的。",
      "Change how you speak", "Right answers still need a team.", "改说话方式", "正确答案仍然需要团队。"),
    q("TF", "A museum label is short. You wish it added…", "博物馆说明很短。你希望它补上……",
      "The evidence", "How they know the date.", "证据", "他们怎么知道年代。",
      "The people", "Whose object this was, and if they agreed.", "人", "这是谁的物件，他们同不同意。"),
    q("TF", "Choosing a science club: olympiad or community air-quality. You pick…", "选科学社：奥赛还是社区空气质量。你会选……",
      "Olympiad", "Hard proofs, ranking, clean right/wrong.", "奥赛", "难证明、排名、干净的对错。",
      "Air-quality", "Sensors on a street where people live.", "空气质量", "装在有人住的街上的传感器。"),
    q("TF", "A classmate cries over a mark. Before you speak, you decide to…", "同学因分数哭了。开口前你决定……",
      "Check the mark scheme", "Maybe the grade is simply wrong.", "查评分标准", "也许分数根本算错了。",
      "Sit with them first", "The number can wait one minute.", "先陪着他们", "数字可以再等一分钟。"),
    q("TF", "An infographic uses a huge number. You ask…", "信息图用了很大的数字。你会问……",
      "Compared to what?", "Baseline, sample, trick axis.", "和什么比？", "基线、样本、骗人的轴。",
      "Who is this number about?", "A village, a class, a body.", "这个数字说的是谁？", "一个村子、一个班、一具身体。"),
    q("TF", "You must recommend a book. You pick the one that is…", "你要推荐一本书。你会选那本……",
      "Most carefully argued", "Claims you can check.", "论证最小心", "主张可以核对。",
      "Most generous to its characters", "People are not used as tools.", "对人物最厚道", "人不是被当成工具。"),
    q("TF", "A coding team ships a feature that works but locks out some students. You…", "编程组上线的功能能跑，但锁住了一些学生。你会……",
      "File a logic bug", "Access rules are part of correctness.", "提一个逻辑 bug", "谁能用也是对不对的一部分。",
      "File a people bug", "Someone cannot join the classwork.", "提一个人的问题", "有人没法加入课堂作业。"),
    q("TF", "When two policies both ‘work’, in civics you vote for the one that is…", "两条政策都能“用”时，公民课上你投……",
      "Better evidenced", "Fewer holes in the data.", "证据更好", "数据漏洞更少。",
      "Kinder in daily life", "Easier to live with on a Monday morning.", "日常更善意", "周一早上更好过。"),

    /* —— JP extra 26–50 —— */
    q("JP", "A three-day exam week. You print…", "三天考试周。你打印……",
      "A hour-by-hour grid", "Each subject has a box. No empty evening.", "一小时一格的表", "每科有格子。晚上不空。",
      "A short list of topics", "You decide the order each morning.", "一张短主题单", "每天早上再决定顺序。"),
    q("JP", "The teacher says ‘hand in anytime this week’. You…", "老师说“这周随时交”。你会……",
      "Pick a day and treat it as due", "Your own deadline is real.", "选定一天当成截止", "你自己的截止日期是真的。",
      "Use the whole week", "The piece might get better on Thursday.", "用满这一周", "周四那一稿可能会更好。"),
    q("JP", "A group doc has no owner. You…", "共享文档没人当主人。你会……",
      "Make a task table", "Names, dates, done/not done.", "做一张任务表", "名字、日期、完成/未完成。",
      "Start writing a section", "Structure can wait until there is text.", "先写一节", "有了文字再谈结构。"),
    q("JP", "You find a better method on day 4 of a 7-day lab. You…", "7 天实验的第 4 天你发现更好方法。你会……",
      "Keep the original method", "Changing now breaks the log.", "保持原方法", "现在改会打乱记录。",
      "Switch", "A better method is worth a messy log.", "换掉", "更好的方法值得一份乱的记录。"),
    q("JP", "Packing for an overnight field trip. Your bag is…", "过夜实地的行李。你的包是……",
      "Listed and ticked", "Kit list from the teacher, plus spares.", "列好并打勾", "老师的装备单，再加备用。",
      "Flexible", "You add things at the door if the weather turns.", "灵活", "天气变了，出门再塞东西。"),
    q("JP", "A long reading. You set…", "一篇长阅读。你设定……",
      "Pages per night", "Thirty pages, then stop, even if it is good.", "每晚页数", "三十页就停，就算好看。",
      "A vibe goal", "Read until the argument is clear, however long.", "一种感觉目标", "读到论点清楚为止，不管多久。"),
    q("JP", "The printer queue is long. Your poster is due tomorrow. You…", "打印队长。海报明天交。你会……",
      "Print a simpler version tonight", "Done is safer than perfect.", "今晚打一个更简单的版本", "完成比完美更安全。",
      "Wait for a better slot", "Colour and size still matter.", "等更好的时段", "颜色和尺寸仍然重要。"),
    q("JP", "A coding sprint: ship Friday. On Wednesday you are…", "编程冲刺：周五交付。周三你已经……",
      "Feature-frozen", "Only bugs. No new ideas.", "功能冻结", "只修 bug。没有新点子。",
      "Still adding a cool extra", "If it fits, it goes in.", "还在加一个酷的额外功能", "能塞就塞。"),
    q("JP", "You keep a homework app. Your board looks like…", "你用作业应用。你的看板像……",
      "Due dates in order", "Red, amber, green. Nothing floats.", "按截止日期排", "红、黄、绿。没有漂着的。",
      "A pile of ‘now’", "You pull the next card when energy matches.", "一堆“现在”", "状态对了再抽下一张。"),
    q("JP", "A teacher offers extra credit with a fuzzy brief. You…", "老师给额外加分，题目很糊。你会……",
      "Ask for the rubric first", "You will not start without ‘done’ defined.", "先要评分标准", "“完成”没定义你就不开始。",
      "Start a draft tonight", "Making will show you what they meant.", "今晚先起草", "做了才知道他们要什么。"),
    q("JP", "Two clubs clash on Thursday. You…", "两个社团周四冲突。你会……",
      "Choose one for the term", "A calendar should not fight itself.", "这学期选定一个", "日历不该自己打架。",
      "Alternate weeks", "You like not locking the whole term.", "隔周去", "你不想把整学期锁死。"),
    q("JP", "Your notes from last month are messy. You…", "上个月的笔记很乱。你会……",
      "Rewrite them into folders now", "Future-you needs a system tonight.", "现在重写成文件夹", "未来的你今晚就需要系统。",
      "Leave them", "You will find the idea when you need it.", "先放着", "需要时你会找到那个想法。"),
    q("JP", "A surprise substitute teacher. You feel best if they…", "突然来了代课老师。如果他们……你最舒服。",
      "Follow the posted plan", "You brought the right books.", "按公布的计划", "你带对了书。",
      "Do something live", "A new task can still be a real lesson.", "做点当场的", "新任务也可以是真课。"),
    q("JP", "You finish an essay early. You…", "作文提早写完。你会……",
      "Submit and close the tab", "Early is the point of the plan.", "提交并关掉标签页", "提早就是计划的意义。",
      "Keep tinkering", "A later sentence might be the true one.", "继续改", "后面那句可能才是真的。"),
    q("JP", "A science logbook must be dated. You…", "科学日志必须写日期。你会……",
      "Write the date before you start", "The page is a contract with time.", "开始前先写日期", "这一页是和时间的契约。",
      "Date it when you remember", "The content matters more than the stamp.", "想起再写日期", "内容比戳子更重要。"),
    q("JP", "Weekend homework: four subjects. Friday night you…", "周末作业：四科。周五晚上你会……",
      "Do the heaviest one", "Clear the mountain while you are fresh.", "做最重的那科", "趁还清醒，先清掉大山。",
      "Do whatever you open first", "Momentum beats the perfect order.", "打开哪科做哪科", "势头比完美顺序重要。"),
    q("JP", "A group wants to brainstorm with no agenda. You…", "小组想无议程头脑风暴。你会……",
      "Add a 20-minute cap and a list", "Chaos with a clock.", "加 20 分钟上限和清单", "有钟的混乱。",
      "Let it run", "The good idea often arrives late.", "让它跑", "好点子常常晚到。"),
    q("JP", "You lose your timetable sheet. Next you…", "课表纸丢了。接下来你会……",
      "Reprint and laminate", "This should not happen twice.", "再打一份并塑封", "不该发生第二次。",
      "Photo the board and go", "Good enough for today.", "拍黑板就走", "今天够用了。"),
    q("JP", "A design cycle: research → idea → make. You like to…", "设计循环：研究→想法→制作。你喜欢……",
      "Finish research before any making", "Gates between stages.", "研究完再动手", "阶段之间有门。",
      "Make a rough while researching", "The object teaches the next search.", "边研究边做粗糙版", "物件会教你下一步查什么。"),
    q("JP", "The exam formula sheet is optional to bring. You…", "考试公式纸可带可不带。你会……",
      "Bring a packed, labelled sheet", "No hunting in the minute you need it.", "带一张装满并标好的", "需要的那一分钟不用找。",
      "Bring a nearly blank sheet", "You will write what the paper asks.", "带一张几乎空白的", "试卷问什么再写什么。"),
    q("JP", "A teacher changes the due date to sooner. You…", "老师把截止日期提前了。你会……",
      "Feel the plan break", "You had the old date in your grid.", "觉得计划裂了", "你的格子里是旧日期。",
      "Rebuild tonight", "Plans are drafts.", "今晚重排", "计划就是草稿。"),
    q("JP", "Last lesson before a holiday. You use it to…", "放假前最后一节。你用来……",
      "Close open tasks", "Inbox zero for homework.", "关掉未完成的任务", "作业收件箱清零。",
      "Start a curiosity tab", "One new question to live with over the break.", "开一个好奇标签", "放假带着一个新问题。"),
    q("JP", "You are asked to plan next term’s revision in September. You…", "九月就要你计划下学期复习。你会……",
      "Fill a year wall-chart", "Months, subjects, checkpoints.", "填一张全年墙表", "月份、科目、检查点。",
      "Wait until you have met the teachers", "The real course is not on last year’s chart.", "等见过老师再说", "真课不在去年的图表上。"),
    q("JP", "A perfect folder system vs a working pile. This week you choose…", "完美文件夹还是能用的一堆。这周你选……",
      "The folder system", "Ten minutes of sorting saves an hour later.", "文件夹系统", "整理十分钟，以后省一小时。",
      "The working pile", "Making is more important than filing today.", "能用的一堆", "今天，做比归档更重要。"),
    q("TF", "A class survey result looks neat but the sample is only your friends. You…", "班级调查结果很整齐，但样本几乎都是你的朋友。你会……",
      "Say the sample is biased", "Friends are not the whole school. The claim is too big.", "指出样本有偏", "朋友不是全校。这个主张太大了。",
      "Ask who was left out", "Whose week this number does not describe.", "问谁被落下了", "这个数字没有描述谁的一周。"),
    q("JP", "You have a free double period. You…", "有一节连堂自习。你会……",
      "Write a mini timetable for the 80 minutes", "Subject A, break, subject B. Then stop.", "给这 80 分钟写个小时间表", "A 科、休息、B 科。然后停。",
      "Follow whatever is unfinished", "Start the pile; switch when it dries up.", "跟没做完的走", "从那堆开始；干了再换。")
  ];

  function shuffle(list) {
    var a = list.slice();
    for (var i = a.length - 1; i > 0; i--) {
      var j = Math.floor(Math.random() * (i + 1));
      var t = a[i];
      a[i] = a[j];
      a[j] = t;
    }
    return a;
  }

  function pick(n) {
    n = n == null ? 20 : n;
    var by = { EI: [], SN: [], TF: [], JP: [] };
    BANK.forEach(function (item) {
      if (by[item.dim]) by[item.dim].push(item);
    });
    var dims = shuffle(["EI", "SN", "TF", "JP"]);
    var base = Math.floor(n / 4);
    var extra = n % 4;
    var counts = {};
    dims.forEach(function (d, i) {
      counts[d] = base + (i < extra ? 1 : 0);
    });
    var deck = [];
    ["EI", "SN", "TF", "JP"].forEach(function (d) {
      deck = deck.concat(shuffle(by[d]).slice(0, counts[d]));
    });
    return shuffle(deck);
  }

  global.MejorQuizBank = BANK;
  global.MejorQuiz = { bank: BANK, pick: pick, size: BANK.length };
})(typeof window !== "undefined" ? window : this);
