/* 15 QS Top-100 overseas universities — popular with Chinese international students. Aug 2026. */
(function (global) {
  global.MejorUniversities = {
    ucl: { short: "UCL", name: "University College London", country: "UK", qs: 9, evidence: "#1 Chinese headcount in the UK (HESA)", intro: "In central London. Known for medicine, architecture (The Bartlett), and education (IOE). A very common UK pick for Chinese students." },
    melbourne: { short: "Melbourne", name: "University of Melbourne", country: "Australia", qs: 19, evidence: "Go8 cluster: 86% of new Chinese students in Australia", intro: "A Group of Eight university in Australia, strong across many subjects. Often on the shortlist for study in Australia." },
    unsw: { short: "UNSW", name: "UNSW Sydney", country: "Australia", qs: 20, evidence: "Go8 cluster", intro: "In Sydney. Especially known for engineering and business. Also in Australia’s Group of Eight." },
    sydney: { short: "Sydney", name: "University of Sydney", country: "Australia", qs: 25, evidence: "Go8 cluster", intro: "One of Australia’s oldest universities. Strong in medicine, law, and arts, with a city campus in Sydney." },
    toronto: { short: "Toronto", name: "University of Toronto", country: "Canada", qs: 29, evidence: "Often named Canada’s top Chinese-student destination", intro: "Canada’s largest research university, downtown Toronto. Often named a top Canadian choice for Chinese students." },
    kcl: { short: "King’s", name: "King’s College London", country: "UK", qs: 31, evidence: "Top 5 UK by Chinese headcount (HESA)", intro: "In London, by the Thames. Known for health, law, war studies, and humanities, with hospitals nearby." },
    edinburgh: { short: "Edinburgh", name: "University of Edinburgh", country: "UK", qs: 34, evidence: "Top 5 UK by Chinese headcount (HESA)", intro: "In Scotland’s capital. Historic, with well-known medicine, informatics, and arts." },
    manchester: { short: "Manchester", name: "University of Manchester", country: "UK", qs: 35, evidence: "~50% of students are mainland Chinese (HESA)", intro: "A large campus in northern England. Big Chinese-student community; strong in science and engineering." },
    columbia: { short: "Columbia", name: "Columbia University", country: "USA", qs: 38, evidence: "~5,035 Chinese students; 3rd in the US (SEVIS)", intro: "An Ivy League school in New York City. Competitive; known for journalism, world affairs, and medicine." },
    ubc: { short: "UBC", name: "University of British Columbia", country: "Canada", qs: 40, evidence: "Often named a top Chinese-student destination in Canada", intro: "In Vancouver, by mountains and ocean. Strong in science, and a frequent Canadian destination for Chinese students." },
    nyu: { short: "NYU", name: "New York University", country: "USA", qs: 55, evidence: "Highest Chinese concentration among major US schools in this set", intro: "Based in New York City. Known for arts (Tisch) and business (Stern). In this set, it has the highest share of Chinese students among the US schools." },
    uiuc: { short: "UIUC", name: "University of Illinois Urbana-Champaign", country: "USA", qs: 70, evidence: "Top 5 US by total foreign-student population (DHS)", intro: "A large US public campus in Illinois. Famous for engineering and computer science. It has no medical school in this set." },
    glasgow: { short: "Glasgow", name: "University of Glasgow", country: "UK", qs: 79, evidence: "Top 5 UK by Chinese headcount (HESA)", intro: "A historic Scottish university. Strong in medicine, law, and arts, and among the UK schools with many Chinese students." },
    southampton: { short: "Southampton", name: "University of Southampton", country: "UK", qs: 87, evidence: "60%+ of students are mainland Chinese (HESA)", intro: "On England’s south coast. Known for engineering and ocean science, with a high share of students from mainland China." },
    sheffield: { short: "Sheffield", name: "University of Sheffield", country: "UK", qs: 92, evidence: "~58% Chinese concentration (HESA)", intro: "In northern England. Known for engineering, architecture, and journalism, with a high share of Chinese students." }
  };
})(typeof window !== "undefined" ? window : this);
